// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    CommonRead: typeof import('./components/table/column/CommonRead.vue')['default']
    CountButton: typeof import('./components/CountButton.vue')['default']
    DateEditor: typeof import('./components/table/column/DateEditor.vue')['default']
    RightContent: typeof import('./components/RightContent/RightContent.vue')['default']
    SaveEditor: typeof import('./components/table/column/SaveEditor.vue')['default']
    SelectEditor: typeof import('./components/table/column/SelectEditor.vue')['default']
    SettingDrawer: typeof import('./components/SettingDrawer/SettingDrawer.vue')['default']
    SortTag: typeof import('./components/Notion/SortTag.vue')['default']
    StringEditor: typeof import('./components/table/column/StringEditor.vue')['default']
    StringRead: typeof import('./components/table/column/StringRead.vue')['default']
    SwitchEditor: typeof import('./components/table/column/SwitchEditor.vue')['default']
    TableColumn: typeof import('./components/table/TableColumn.vue')['default']
    TableConfigurator: typeof import('./components/TableConfigurator.vue')['default']
    ViewTable: typeof import('./components/table/ViewTable.vue')['default']
    WebTerminal: typeof import('./components/WebTerminal.vue')['default']
  }
}

export { }
