// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountButton: typeof import('./components/CountButton.vue')['default']
    ExcelTable: typeof import('./components/ExcelTable.vue')['default']
    NotionTable: typeof import('./components/Notion/NotionTable.vue')['default']
    RightContent: typeof import('./components/RightContent/RightContent.vue')['default']
    SettingDrawer: typeof import('./components/SettingDrawer/SettingDrawer.vue')['default']
    SortTag: typeof import('./components/Notion/SortTag.vue')['default']
    TableConfig: typeof import('./components/TableConfig.vue')['default']
    ViewTable: typeof import('./components/ViewTable.vue')['default']
  }
}

export { }
